services: 
  api_gateway:
    build: ./api_gateway/
    ports:
      - '4000:4000'
    volumes:
      - ./api_gateway/src:/usr/src/app/src
      - ./api_gateway/node_modules:/usr/src/app/node_modules
    
    command: npm run start:dev 
  users_microservice:
     build: ./users-microservice
     command: npm run start:dev
     volumes:
      - ./users-microservice/src:/usr/src/app/src
      - ./users-microservice/node_modules:/usr/src/app/node_modules
  payment_microservice:
    build: ./payment-microservice/
    env_file:
      - ./payment-microservice/.env
    volumes:
      - ./payment-microservice/src:/usr/src/app/src
      - ./payment-microservice/node_modules:/usr/src/app/node_modules
    command: npm run start:dev
     
  nats:
    image: nats
    ports:
      - '4222:4222'
      
     

    
  mysqldb:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=Blaise@123
      - MYSQL_PORT=3307
      - MYSQL_DATABASE=payment_system 
      - MYSQL_TCP_PORT=3307

    