services: 
  api_gateway:
    build: ./api_gateway/
    ports:
      - '4000:4000'
    volumes:
      - ./api_gateway/src:/usr/src/app/src
    
    command: npm run start:dev 
  users_microservice:
     build: ./users-microservice
     command: npm run start:dev
     volumes:
      - ./users-microservice/src:/usr/src/app/src
  payment_microservice:
    build: ./payment-microservice/
    volumes:
      - ./payment-microservice/src:/usr/src/app/src
    command: npm run start:dev
     
  nats:
    image: nats
    ports:
      - '4222:4222'
      
     

    

     
    